spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/open_code?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
      resolve-lazily: false


